models/Solicitacao.php
<?php

namespace app\models;

use Yii;
use app\models\Usuario;
use app\models\Atividade;
use marqu3s\behaviors\SaveGridFiltersBehavior;


/**
 * This is the model class for table "solicitacao".
 *
 * @property integer $id
 * @property string $descricao
 * @property string $dtInicio
 * @property string $dtTermino
* @property integer $horasLancadas 
 * @property integer $horasComputadas
 * @property integer $horasMaxAtiv
 * @property string $observacoes
 * @property string $status
 * @property integer $atividade_id
 * @property integer $periodo_id
 * @property integer $solicitante_id
 * @property integer $aprovador_id
 * @property date $created_at
 */
class Solicitacao extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
	 
	 public $name;
	 
    public static function tableName()
    {
        return 'solicitacao';
    }

    //RELACIONAMENTO com a tabela USUARIO
    /**
    * @return \yii\db\ActiveQuery
    */
    public function getUsuario()
    {
        return $this->hasOne(Usuario::className(), ['id' => 'solicitante_id']);
    }

    //RELACIONAMENTO com a tabela ATIVIDADE
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAtividade()
    {
        return $this->hasOne(Atividade::className(), ['id' => 'atividade_id']);
    }

    //RELACIONAMENTO com a tabela PERIODO
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeriodo()
    {
        return $this->hasOne(Periodo::className(), ['id' => 'periodo_id']);
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descricao', 'horasLancadas','dtInicio', 'dtTermino', 'status', 'atividade_id', 'solicitante_id'], 'required', 'message'=>'Este campo é obrigatório'],
            //[['dtInicio', 'dtTermino', 'solicitante_id'], 'safe'],
			[['solicitante_id', 'aprovador_id'], 'safe'],
			['dtInicio','validateDates'],
			['descricao','validateSolicitacao'],
//			[['dtInicio','dtTermino'], 'date', 'format' => 'php:Y-m-d', 'message'=> 'O formato desta data é inválido'],
//            ['dtTermino', 'compare', 'compareAttribute' => 'dtInicio', 'operator' => '>=', 'message'=> 'A data de término deve ser igual ou maior que a data de início'],
            [['atividade_id'], 'integer', 'message'=>'Este campo deve ser inteiro'],
			[['horasLancadas'], 'integer', 'min'=> 1, 'message'=>'Horas deve ser inteiro', 'tooSmall' => 'Horas computadas deve ser maior que zero'],
            [['descricao', 'observacoes'], 'string', 'max' => 100, 'message'=>'Este campos possui tamanho máximo igual a 100 caracteres', 'tooLong'=>'Este campos possui tamanho máximo igual a 100 caracteres'],
            [['status'], 'string', 'max' => 20],
            [['arquivo'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, pdf', 'wrongExtension'=>'Formato incorreto: Aceito somente: png, jpeg e PDF'],
           // [['horasComputadas'], 'horas_check', 'message'=>'As horas computadas não pode ser maior que a hora máxima por atividade'],
            //[['horasComputadas'], 'horas_calc', 'message'=>'Quantidade maxima para atividade foi atingida']
        ];
    }
    
    /*
     * Verifica se a quantidade informada de horas computadas para a Atividade
     * Não ultrapassou o limite daquela atividade
     */
    public function horas_check($attribute, $params) {
        $horasAtual = $this->horasComputadas;
        $atividadeAtual = Atividade::findOne($this->atividade_id);

        if ($horasAtual > $atividadeAtual->max_horas) {
            $this->addError($attribute,'As horas computadas não pode ser maior que a hora máxima por atividade');
        }
    }

    public function horas_calc($attribute, $params){
        $horasComputadas  = (int) $this->horasComputadas;

        $solicitante_id = Yii::$app->user->identity->id ;

        //calcula a quantidade de horas que o Aluno
        //ja tem naquela atividade...
        $cmd = Yii::$app->db->createCommand("SELECT SUM(horasComputadas) AS soma
                    FROM solicitacao AS S
                    WHERE S.atividade_id = $this->atividade_id
                    AND solicitante_id = $solicitante_id
					AND status = 'Deferida'
                ");

        $hsProduzidas = (int) $cmd->queryScalar();
        $Atividade = Atividade::findOne($this->atividade_id);
		$MaxHorasAtividade = (int) $Atividade->max_horas;
		
		$Grupo = Grupo::findOne(['id' => $Atividade->grupo_id]);
        $MaxHorasGrupo = (int) $Grupo->max_horas;

        if($hsProduzidas == $MaxHorasGrupo)
        {
            $this->addError($attribute,"As horas para esse grupo de atividade já chegaram no máximo.");

        }else if(($hsProduzidas + $horasComputadas) > $MaxHorasGrupo){
            $diferenca = (int) ($MaxHorasGrupo - $hsProduzidas);

            $this->addError($attribute,"As horas computadas não podem ultrapassar $diferenca horas que faltam para alcançar o limite desse grupo de atividade.");
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Número',
            'descricao' => 'Descrição da Solicitação',
            'dtInicio' => 'Data de Início',
            'dtTermino' => 'Data de Término',
            'horasComputadas' => 'Horas Lançadas',
			'horasComputadas' => 'Horas Computadas',
            'observacoes' => 'Observações',
            'status' => 'Status',
            'atividade_id' => 'Atividade',
            'solicitante_id' => 'Solicitante',
            'aprovador_id' => 'Aprovador',
            'anexo_id' => 'Anexo',
            'anexoOriginalName' => 'Arquivo Anexo',
            'created_at' => 'Criado Em'
        ];
    }
	
	function checkData($data) {
		return (date('d-m-Y', strtotime($data)) == $data);
    }

	public function validateDates(){
		$erro = false;
		
		if(!Solicitacao::checkData($this->dtInicio)){
			$this->dtInicio = "";
			$this->addError('dtInicio','Por favor, informe uma data de início válida no formato DD-MM-AAAA.');
			$erro = true;
		}
		else{
			$this->dtInicio = Yii::$app->formatter->asDate(strtotime($this->dtInicio), 'php:Y-m-d');
		}
		if(!Periodo::checkData($this->dtTermino)){
			$this->dtTermino = "";
			$this->addError('dtTermino','Por favor, informe uma data de término válida no formato DD-MM-AAAA.');
			$erro = true;
		}	
		else{
			$this->dtTermino = Yii::$app->formatter->asDate(strtotime($this->dtTermino), 'php:Y-m-d');
		}
		
		if($erro == false){
			
			if(strtotime($this->dtInicio) > strtotime(date("Y-m-d"))){
				$this->addError('dtInicio','Por favor, informe uma data de início anterior à data atual');
			}
			if(strtotime($this->dtTermino) > strtotime(date("Y-m-d"))){
				$this->addError('dtTermino','Por favor, informe uma data de término anterior à data atual');
			}
			if(strtotime($this->dtTermino) < strtotime($this->dtInicio)){
				$this->addError('dtInicio','Por favor, informe uma data de início anterior ou igual à data de término');
				$this->addError('dtTermino','Por favor, informe uma data de término posterior ou igual à data de início');
			}
		}
	}	
	
	public function validateSolicitacao(){
				
		$repetida = Solicitacao::findOne(['descricao' => $this->descricao, 'dtInicio' => $this->descricao, 'dtTermino' => $this->dtTermino, 'atividade_id' => $this->atividade_id, 'solicitante_id' => $this->solicitante_id]);
		var_dump($repetida);
		var_dump($this->descricao);
		
		if($repetida){
			$this->addError('descricao','Já existe uma solicitação cadastrada com esses dados.');
		}
	}	
	
	public function behaviors()
	{
		return [
			//'saveGridPage' =>[
//				'class' => SaveGridPaginationBehavior::className(),
	//			'sessionVarName' => self::className() . 'GridPage'
		//	],
			'saveGridFilters' =>[
				'class' => SaveGridFiltersBehavior::className(),
				'sessionVarName' => self::className() . 'GridFilters'
			]
		];
	}
}

controllers/SolicitacaoController.php
<?php

namespace app\controllers;

use app\models\Curso;
use app\models\Grupo;
use app\models\Periodo;
use Yii;
use app\models\Solicitacao;
use app\models\SolicitacaoSearch;
use app\models\Atividade;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * SolicitacaoController implements the CRUD actions for Solicitacao model.
 */
class SolicitacaoController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','index', 'update', 'view', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create','index', 'update', 'view', 'delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if(!Yii::$app->user->isGuest)
                            {
                                return Yii::$app->user->identity->perfil == 'Coordenador' ;
                            }
                        }
                    ],[
                        'actions' => ['index', 'view', 'update', 'delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if(!Yii::$app->user->isGuest)
                            {
                                return Yii::$app->user->identity->perfil == 'Secretaria' ;
                            }
                        }
                    ],
                    [
                        'actions' => ['create', 'index', 'update', 'view', 'delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if(!Yii::$app->user->isGuest)
                            {
                                return Yii::$app->user->identity->perfil == 'Aluno' ;
                            }
                        }
                    ],                    
                ],
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Solicitacao models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SolicitacaoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Solicitacao model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
		
		$atividade = Atividade::findOne($model->atividade_id);
        if ($atividade != null)
            $model->atividade_id = $atividade->codigo."-".$atividade->nome;
		
		return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Solicitacao model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Solicitacao();
        $model->created_at = date('Y-m-d');
		
		$periodo = Periodo::findOne(['isAtivo' => 1]); //Periodo::getPeriodoAtivo();
		$model->periodo_id = $periodo->id;
		
       if ($model->load(Yii::$app->request->post())){ // && $model->save()) {

            //$model->dtInicio = Yii::$app->formatter->asDate($model->dtInicio, 'php:Y-m-d');
            //$model->dtTermino = Yii::$app->formatter->asDate($model->dtTermino, 'php:Y-m-d');

            if(Yii::$app->user->identity->perfil == 'Aluno'){
                $model->solicitante_id = Yii::$app->user->identity->id;
            }

            $file = UploadedFile::getInstance($model, 'arquivo');

            if(isset($file)){
                
                
                $file_name = Yii::$app->user->identity->id . '_' . rand(1, 999999);
                $file_name = $file_name . '.' . $file->extension;     
                $file->saveAs('uploads/' . $file_name);
                $model->arquivo = $file;
                
                //atualiza os dados do nome no model solicitacao
                
                $model->anexoOriginalName = $file->baseName . '.' . $file->extension ;
                $model->anexoHashName = $file_name ;
                $model->arquivo = null ;     //estava dando erro na hora de salvar  
            }

            if($model->save())
				return $this->redirect(['view', 'id' => $model->id]);
			else
				return $this->render('create', ['model' => $model,]);
			
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Solicitacao model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
        if ($model->load(Yii::$app->request->post())){ 
			if($model->horasLancadas < $model->horasComputadas)
				$model->horasComputadas = $model->horasLancadas;
				
			if($model->save())
				return $this->redirect(['view', 'id' => $model->id]);
			else
				return $this->render('update', ['model' => $model,]);
			
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Solicitacao model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index', 'success' => 'Solicitação excluída com sucesso']);
    }
    
    public function actionField($id){
        $posts = Atividade::findOne($id);
        
        echo $posts->max_horas;
    }



     public function actionSubmit()
    {

        $selection = (array)Yii::$app->request->post('selection');//typecasting
        $action = Yii::$app->request->post('action');

        $status = '';

        if(!$selection){
            return $this->redirect(['index','error' => 'Selecione uma solicitação']);
        }

        if ($action == 'Submeter') {
            $status = 'Submetida';
      //  } else if ($_POST['action'] == 'Arquivar') {
            //$status = 'Arquivada';
        } else if ($_POST['action'] == 'Deferir') {
            $status = 'Deferida';
        }else if ($_POST['action'] == 'Indeferir'){
            $model->aprovador_id = Yii::$app->user->identity->id;
			$status = 'Indeferida';
        }else{
            $status = 'Pre-Aprovada';
        }
        
        foreach($selection as $id){

            $s = Solicitacao::findOne((int)$id); //make a typecasting

            if(Yii::$app->user->identity->perfil=='Aluno')
            {
                if($s->status=='Aberto' || $s->status=='Indeferida')
                {
                    $s->status = $status;
                }
				else{
					return $this->redirect(['index','error' => 'Apenas solicitações com status ABERTA ou INDEFERIDA podem ser submetidas']);
				}
            }

            if(Yii::$app->user->identity->perfil=='Secretaria')
            {
                if($s->status=='Submetida')
                {
                    $s->status = $status;
					$s->aprovador_id = Yii::$app->user->identity->id;
                }
				else{
					return $this->redirect(['index','error' => 'Apenas solicitações com status SUBMETIDA podem ser Avaliadas']);
				}
				
            }

            if(Yii::$app->user->identity->perfil=='Coordenador')
            {
                if($s->status=='Pre-Aprovada' || $s->status=='Submetida')
                {
                    $s->status = $status;
					$s->aprovador_id = Yii::$app->user->identity->id;
					$s->horasComputadas = $this->computarHoras($s);
  //                  $s->save();
                }
				//else if(($s->status=='Deferida' || $s->status=='Indeferida') && $status == 'Arquivada'){
                  //  $s->status = $status;
                    //$s->save();
				//}
				else{
					return $this->redirect(['index','error' => 'Apenas solicitações com status SUBMETIDAS ou PRÉ-APROVADAS podem ser Avaliadas']);
				}
            }

            $s->save(false);
        }
		//$this->mensagens('success', 'Sucesso', 'Solicitação pré-aprovada com sucesso.');
		//Yii::$app->session->setFlash('success', "Your message to display");
        return $this->redirect(['index','success' => 'Solicitação(ões) processada(s) com sucesso']);
    }

    /**
     * Finds the Solicitacao model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Solicitacao the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Solicitacao::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

/**
     * Lists Report with all Solicitacao.
     * @return mixed
     */
    
	
    /*public function actionRelatorio()
    {
        $cmd = Yii::$app->db->createCommand("SELECT usuario.id as id, usuario.name as nome,usuario.matricula as matricula, periodo.codigo as periodo,
                                                    (
                                                        SELECT COALESCE(sum(solicitacao.horasComputadas), 0)

views/solicitacao/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SolicitacaoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="solicitacao-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'descricao') ?>

    <?= $form->field($model, 'dtInicio') ?>

    <?= $form->field($model, 'dtTermino') ?>

    <?= $form->field($model, 'horasComputadas') ?>

    <?php // echo $form->field($model, 'horasMaxAtiv') ?>

    <?php // echo $form->field($model, 'observacoes') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'atividade_id') ?>

    <?php // echo $form->field($model, 'periodo_id') ?>

    <?php // echo $form->field($model, 'solicitante_id') ?>

    <?php // echo $form->field($model, 'aprovador_id') ?>

    <?php // echo $form->field($model, 'anexo_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/solicitacao/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Solicitacao */

$this->title = 'Cadastro de Solicitação';

?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
       <li><a href="?r=solicitacao/index"><i class="fa fa-download"></i> Solicitações</a></li>
        <li class="active"><a href="?r=solicitacao/create">Cadastro</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success"> 
<div class="solicitacao-create box-body">


    <?= $this->render('_form', [
        'model' => $model, 
    ]) ?>

</div>
</div>
</section>

views/solicitacao/relatorio - Copia.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\DetailView;
use app\models\Periodo;

/* @var $this yii\web\View */
/* @var $model app\models\Solicitacao */

$this->title = 'Relatório';
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=solicitacao/index"><i class="fa fa-download"></i> Solicitações</a></li>
        <li class="active"><a href="?r=solicitacao/view">Visualizar</a></li>
    </ol>
</section>
 <label>Selecione o período:</label>  
            
 <?= Html::dropDownList('periodo', ['2015/01', '2015/02','2016/01', '2016/02'] ) ?>

 
<section class="content">

    <div class="box box-success">
        <div class="box-header">
            <h4>Clique em cima da matricula para copiar para a área de transfêrencia.</h4>
        </div>
        <div class="solicitacao-view box-body">

            <!--<table class="table table-hover table-bordered">
                <thead>
                    <th>Aluno</th>
                    <th>Matricula</th>
                    <th>Período</th>
                    <th>Ensino</th>
                    <th>Pesquisa</th>
                    <th>Extensão</th>
                </thead>

                <?php foreach($resultado as $res) {?>
                <tr>
                    <td><?= $res['nome'] ?></td>
                    <td>
                        <a href="#">
                            <span class="fa fa-clipboard" onclick="copyToClipboard(this)"><?= $res['matricula'] ?></span>
                        </a>
                    </td>
                    <td><?= $res['periodo'] ?></td>
                    <td><?= $res['ensino'] ?></td>
                    <td><?= $res['pesquisa'] ?></td>
                    <td><?= $res['extensao'] ?></td>
                    
                </tr>
                <?php } ?>
            </table>
-->

<?=Html::beginForm(['solicitacao/submit'],'post');?>
        <div class="row">
            <div class="col-xs-4">     
                <?php if(Yii::$app->user->identity->perfil == 'Coordenador' || Yii::$app->user->identity->perfil == 'Aluno'){ ?>
                     <?= Html::a('Nova Solicitação', ['create'], ['class' => 'btn btn-success']) ?>
                <?php } ?>
            </div>

            <div class="col-xs-8"> 
                <div class="pull-right">       
                    <?php if(Yii::$app->user->identity->perfil == 'Coordenador'){ ?>
                        <!--<?= Html::submitButton('Arquivar ', ['class' => 'btn btn-primary', 'name' => 'action', 'value' => 'Arquivar']) ?>-->
                        <?= Html::submitButton('Indeferir ', ['class' => 'btn btn-danger', 'name' => 'action', 'value' => 'Indeferir']) ?>
                        <?= Html::submitButton('Deferir ', ['class' => 'btn btn-success', 'name' => 'action', 'value' => 'Deferir']) ?>
                    <?php } ?>

                    <?php if(Yii::$app->user->identity->perfil == 'Secretaria'){ ?>
                        <?= Html::submitButton('Indeferir ', ['class' => 'btn btn-danger', 'name' => 'action', 'value' => 'Indeferir']) ?>
                        <?= Html::submitButton('Pré-aprovar ', ['class' => 'btn btn-success', 'name' => 'action', 'value' => 'PreAprovar']) ?>
                    <?php } ?>
                                 
                    <?php if(Yii::$app->user->identity->perfil == 'Aluno'){ ?>
                        <?= Html::submitButton('Submeter', ['class' => 'btn btn-info', 'name' => 'action', 'value' => 'Submeter']);?>
                    <?php } ?>
                </div>
            </div>
        </div>
        
        <hr/>

        <label>Selecione o filtro:</label>  
            
       <?php 
			if(Yii::$app->user->identity->perfil == 'Aluno')
				//$opcoes = array ('Aberto' => 'Aberto', 'Submetida' => "Submetida", 'Pre-aprovada' => "Pre-aprovada", 'Indeferida' => "Indeferida", 'Deferida' => "Deferida", 'Arquivada' => "Arquivada");
				$opcoes = array ('Aberto' => 'Aberto', 'Submetida' => "Submetida", 'Pre-aprovada' => "Pre-aprovada", 'Indeferida' => "Indeferida", 'Deferida' => "Deferida");
			else
				//$opcoes = array ('Submetida' => "Submetida", 'Pre-aprovada' => "Pre-aprovada", 'Indeferida' => "Indeferida", 'Deferida' => "Deferida", 'Arquivada' => "Arquivada");
				$opcoes = array ('Submetida' => "Submetida", 'Pre-aprovada' => "Pre-aprovada", 'Indeferida' => "Indeferida", 'Deferida' => "Deferida");
				
			
		?>

         <hr/>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
				'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\CheckboxColumn',
                        'checkboxOptions' => function ($dataProvider, $key, $index, $column) {
                            return ['value' => $dataProvider['id']];
                        }
                    ],
					['label' => 'Número', 'attribute'=>'id', 'value'=>'id','contentOptions' =>['style' => 'width:100px'],],
					['label' => 'Nome do Aluno', 'attribute' => 'name', 'value' => 'name', 'visible' => Yii::$app->user->identity->perfil <> 'Aluno'],
					//'atividade_id',
					['attribute'=>'atividade_id', 'label'=>'Atividade', 'value' => function ($model) {  return $model->atividade->codigo.': '.$model->atividade->nome;  }  ],
					//'grupo',
                    'descricao',
                    [
                        'attribute' => 'Inicio',
                        'format'    => ['date', 'php:d-m-Y'],
                        'value'     => 'dtInicio',
						'contentOptions' =>['style' => 'width:100px'],
                    ],
                    [
                        'attribute' => 'Termino',
                        'format'    => ['date', 'php:d-m-Y'],
                        'value'     => 'dtTermino',
						'contentOptions' =>['style' => 'width:100px'],
                    ],
                    ['label' => 'Horas Solicitadas', 'attribute'=>'horasLancadas', 'value'=>'horasLancadas','contentOptions' =>['style' => 'width:100px'],],
					['label' => 'Horas Computadas', 'attribute'=>'horasComputadas', 'value'=>'horasComputadas','contentOptions' =>['style' => 'width:100px'],],
					[   'label' => 'Status',
						'attribute' => 'status',
						'filter'=> $opcoes,
						'value' => 'status',
						'contentOptions' =>['style' => 'width:100px'],
					],
                    ['class' => 'yii\grid\ActionColumn',
                        'contentOptions' =>['style' => 'width:100px'],
						'template' =>  Yii::$app->user->identity->perfil == 'Secretaria' ? '{view}{update}{delete}' : '{view}{update}{delete}',
                        'buttons' => [
                            'update' => function ($url, $model) {
                                return \yii\helpers\Html::a('<span class="label label-primary"><i class=" fa fa-pencil"></i></span>&nbsp;',
                                    (new yii\grid\ActionColumn())->createUrl('solicitacao/update', $model, $model['id'], 1), [
                                        'title' => Yii::t('yii', 'Editar'),
                                        'data-method' => 'post',
                                        'data-pjax' => '0',
                                    ]);
                            },
                            'delete' => function ($url, $model) {
                                return \yii\helpers\Html::a('<span class="label label-danger"><i class=" fa fa-trash"></i></span>',
                                    (new yii\grid\ActionColumn())->createUrl('solicitacao/delete', $model, $model['id'], 1), [
                                        'title' => Yii::t('yii', 'Apagar'),
                                        'data-method' => 'post',
                                        'data-pjax' => '0',
										'data-confirm'=> 'Confirmar exclusão da solicitação?'										
                                    ]);
                            },
                            'view' => function ($url, $model) {
                                return \yii\helpers\Html::a('<span class="label label-success"><i class=" fa fa-search"></i>&nbsp;</span>&nbsp;',
                                    (new yii\grid\ActionColumn())->createUrl('solicitacao/view', $model, $model['id'], 1), [
                                        'title' => Yii::t('yii', 'Ver'),
                                        'data-method' => 'post',
                                        'data-pjax' => '0',
                                    ]);
                            },


                        ]
                    ],

                ],
            ]); ?>

    <?= Html::endForm();?> 

        </div>
    </div>
</section>

<!-- Script para Copiar para a area de transf. -->
<script>
    function copyToClipboard(element) {
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val($(element).text()).select();

        document.execCommand("copy");

        $temp.remove();

    }
</script>

views/solicitacao/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Solicitacao */

$this->title = $model->descricao;

?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=solicitacao/index"><i class="fa fa-download"></i> Solicitações</a></li>
        <li class="active"><a href="?r=solicitacao/update">Editar</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success"> 
<div class="solicitacao-update box-body">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>
</section>