models/Atividade.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "atividade".
 *
 * @property integer $id
 * @property string $codigo
 * @property string $nome
 * @property integer $max_horas
 * @property integer $curso_id
 * @property integer $grupo_id
 */
class Atividade extends \yii\db\ActiveRecord
{
 
	public $curso;
	public $grupo;
	
	/**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'atividade';
    }

    public function getSolicitacoes()
    {
        return $this->hasMany(Solicitacao::className(), ['atividade_id' => 'id']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['codigo', 'nome', 'max_horas', 'curso_id', 'grupo_id'], 'required', 'message'=> 'Este campo é obrigatório'],
            [['curso_id', 'grupo_id'], 'integer', 'message'=>'Este campo deve ser numérico'],
			[['max_horas'], 'integer', 'min'=> 1, 'max'=> 10000, 'message'=>'Máximo de horas deve ser inteiro', 'tooSmall' => 'Máximo de horas deve ser maior que zero','tooBig' => 'Máximo de horas deve ser menor que 10.000',],
            [['codigo'], 'string', 'max' => 5, 'tooLong'=>'Código deve ser tamanho máximo de 5 caracteres'],
            [['nome'], 'string', 'max' => 100, 'tooLong'=>'Nome da atividade deve ser tamanho máximo de 100 caracteres'],
			['nome','validateAtividade'],
			['codigo','validateCodigo'],
			['max_horas','validateHora'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'codigo' => 'Código',
            'nome' => 'Nome',
            'max_horas' => 'Máximo de Horas',
            'curso_id' => 'Curso',
            'grupo_id' => 'Grupo',

        ];
    }
	
	public function validateAtividade(){
		
		$atividadeIgual = Atividade::findOne(['codigo' => $this->codigo, 'nome' => $this->nome, 'curso_id' => $this->curso_id]);
		
		if($atividadeIgual && $atividadeIgual->id != $this->id){
			$this->addError('nome','Já existe atividade com este código e nome associada ao curso corrente');
		}
	}	
	
	public function validateCodigo(){
		
		$codigoIgual = Atividade::findOne(['codigo' => $this->codigo, 'curso_id' => $this->curso_id]);
		
		if($codigoIgual && $codigoIgual->id != $this->id){
			$this->addError('codigo','Já existe código com este valor associado ao curso corrente');
		}
	}	
	
	public function validateHora(){
		
		$curso = Curso::findOne($this->curso_id);
		
		if($this->max_horas > $curso->max_horas){
			$this->addError('max_horas','As horas são superiores às horas máximas previstas para o curso');
		}
	}
}

controllers/AtividadeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Atividade;
use app\models\Curso;
use app\models\Grupo;
use app\models\AtividadeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * AtividadeController implements the CRUD actions for Atividade model.
 */
class AtividadeController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','index', 'update', 'view', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create','index', 'update', 'view', 'delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if(!Yii::$app->user->isGuest)
                            {
                                return Yii::$app->user->identity->perfil == 'Coordenador' ;
                            }
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Atividade models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AtividadeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Atividade model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		
		$model = $this->findModel($id);
		
		$curso = Curso::findOne($model->curso_id);
        if ($curso != null)
            $model->curso_id = $curso->codigo."-".$curso->nome;
		
		$grupo = Grupo::findOne($model->grupo_id);
        if ($grupo != null)
            $model->grupo_id = $grupo->codigo."-".$grupo->nome;
		
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Atividade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Atividade();

        $model->curso_id = Yii::$app->user->identity->curso_id;

        $searchModel = new AtividadeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'dataProvider' => $dataProvider
            ]);
        }
    }

    /**
     * Updates an existing Atividade model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Atividade model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Atividade model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Atividade the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Atividade::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/atividade/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Grupo;
use app\models\Curso;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Atividade */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="atividade-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="col-md-4">

        <?= $form->field($model, 'codigo')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'max_horas')->textInput() ?>

        <?php
          //echo $form->field($model, 'curso_id')->dropDownList(ArrayHelper::map(Curso::find()->all(), 'id', 'nome'), ['prompt'=>'Selecione']);
        ?>

        <?php
          echo $form->field($model, 'grupo_id')->dropDownList(ArrayHelper::map(Grupo::find()->all(), 'id', 'nome'), ['prompt'=>'Selecione']);
        ?>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Salvar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::a('Cancelar', ['atividade/index'], ['class' => 'btn btn-danger']) ?>
        </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/atividade/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AtividadeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="atividade-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'codigo') ?>

    <?= $form->field($model, 'nome') ?>

    <?= $form->field($model, 'max_horas') ?>

    <?= $form->field($model, 'curso_id') ?>

    <?php // echo $form->field($model, 'grupo_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/atividade/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Atividade */

$this->title = 'Cadastro de Atividade';

?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=atividade/index"><i class="fa fa-tasks"></i> Atividades</a></li>
        <li class="active"><a href="?r=atividade/create">Cadastro</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success">
<div class="atividade-create box-body">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>
 </section>

views/atividade/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AtividadeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Atividades';
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=atividade/index"><i class="fa fa-tasks"></i> Atividades</a></li>
        <li class="active"><a href="?r=atividade/index">Lista</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success">
    <div class="atividade-index box-body">

        <p>
            <?= Html::a('Nova Atividade', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
            'summary'=>'',
            'columns' => [
                'codigo',
				'nome',
                'max_horas',
				//'curso',
				[   'label' => 'Grupo',
                'attribute' => 'grupo',
                'filter'=> array (1 => "Ensino",2 => "Pesquisa",3 => "Extensão"),
				'value' => 'grupo',
            ],

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>

    </div>
</div>
</section>

views/atividade/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Atividade */

$this->title = $model->nome;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=atividade/index"><i class="fa fa-tasks"></i> Atividades</a></li>
        <li class="active"><a href="?r=atividade/update">Editar</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success">
<div class="atividade-update box-body">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>
</section>

views/atividade/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Atividade */

$this->title = $model->nome;?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=atividade/index"><i class="fa fa-tasks"></i> Atividades</a></li>
        <li class="active"><a href="?r=atividade/index">Visualizar</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="atividade-view box-body">

            <p>
				<?= Html::a('<span class="glyphicon glyphicon-arrow-left"></span> Voltar', ['index'], ['class' => 'btn btn-warning']) ?>
                <?= Html::a('Editar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Excluir', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    //'id',
                    'codigo',
                    'nome',
                    'max_horas',
                    'curso_id',
                    'grupo_id',
                ],
            ]) ?>

        </div>
    </div>
</section>