models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 */
class LoginForm extends Model
{
    public $usrname;
    public $cpf;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['cpf', 'password'], 'required', 'message'=> 'Este campo é obrigatório'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Usuario ou Senha Inválidos..');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = Usuario::findByCpf($this->cpf);
        }

        return $this->_user;
    }
}

controllers/LoginController.php
<?php
namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Curso;
use app\models\CursoSearch;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Usuario;
use app\models\UsuarioSearch;
use app\models\UsuarioForm;
use yii\helpers\Html;
use yii\helpers\Url;

use App\Anexo;

class LoginController extends Controller
{
    public $layout = 'login';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['index', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['GET'],
                ],
            ],
        ];
    }
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    public function actionIndex()
    {
        return $this->render('login');
    }

    public function actionLogin()
    {
        $route = "site/error";

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            if (Yii::$app->user->identity->isAdmin == 1) {
                $route = $this->redirect(["curso/index"]);
            }

            if (Yii::$app->user->identity->perfil == "Secretaria") {
                $route = $this->redirect(["solicitacao/index"]);
            }

            if (Yii::$app->user->identity->perfil == "Aluno") {
                $route = $this->redirect(["dashboard/index"]);
            }

            if (Yii::$app->user->identity->perfil == "Coordenador") {
                $route = $this->redirect(["dashboard/index"]);
            }

            if (Yii::$app->user->identity->perfil == "Professor") {
                $route = $this->redirect(["monitoria/professor"]);
            }

            return $route;

        }
        
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionAnexo()
    {
        return 'teste...';
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

      /* **** ***************************
    * Novo usuario via Webservice
    * ult.mod: 17/01/2016
    * *** ************************** */
    public function actionNovousuario()
    {

        if ( Yii::$app->request->post() ) 
        {
            
            $model = new Usuario();
			$model->scenario = 'insert';

            //verifica se o CPF já está cadastrado
            $usuario = Usuario::find()->where(['cpf' => Yii::$app->request->post('cpf') ])->one();

            if( $usuario != null )
            {
                return $this->render('novousuario', ['erro'=>'Usuário já cadastrado']);
            }

            /* * pega os dados do webservice do cpd * */
            $cpf = Yii::$app->request->post('cpf');

            //$link = 'http://200.129.163.9:80801/ecampus_teste/servicos/getPessoaValidaSIE?cpf=' ;
			$token = "98df1b3e0103f57a9817d675071504ba-".date("Y-m-d");
			$tokenMD5 = MD5($token);
			$link = 'http://200.129.163.42:8080/ws/rest/sie/json/sieJSON/icomp?cpf='.$cpf.'&hshtkn='.$tokenMD5;

           // $link = $link . Yii::$app->request->post('cpf');

            $webservice = @file_get_contents($link);

            // Verifica se o WS está disponivel
            //Caso negativo ele exibe o formulario em branco
            if($webservice == null)
            {
                $model->cpf = Yii::$app->request->post('cpf');
                $model->isNewRecord = true;
				$model->isAtivo = 1;
                return $this->render('create', ['model' => $model ]);
            }
            
            $dados = json_decode($webservice, true);

            //verifica se encontrou o CPF no ecampus
            if( isset( $dados['CPF inválido ']) )
            {
                return $this->render('novousuario', ['erro'=>'CPF não encontrado ou inválido']);
            }

            //Para alunos com mais de uma matricula
            //procura a matricula ativa
            //se nenhuma matrica estiver ativa.. o sistema volta a tela inicia
            $atual = null;
            
            foreach($dados as $aluno)
            {
                if($aluno["ativo"]=="true" && isset($aluno["matriculaAluno"]))
                {
                    $atual = $aluno;
                }
            }

            if($atual==null)
            {
                return $this->render('novousuario', ['erro'=>'O CPF não conrresponde a um aluno ativo na UFAM']);
            }
            
            // Adiciona os dados do aluno no model e redireciona p 
            // tela de cadastro...
            $model->name        = $atual['nome'] ;
            $model->cpf         = Yii::$app->request->post('cpf');
            $model->email       = $atual['email'];
            $model->matricula   = $atual['matriculaAluno'];
            $curso_sigla = $atual['curso'];
            
            //Verifica se o curso pertence aos cursos
            //cadastrados
            $curso = Curso::find()->where(['codigo' => $curso_sigla])->one();
			
            if($curso == null)
            {
               // throw new NotFoundHttpException('O Curso não está cadastrado para este aluno');
			   return $this->render('create', ['erro' => 'O curso associado ao aluno identificado não foi encontrado. Escolha o curso na lista acima.', 'model' => $model ]);                 
            }

            $model->curso_id = $curso->id;
            $model->isNewRecord = false;
            
			return $this->render('create', ['model' => $model ]);                 

        }
        // se a requisicao for do tipo GET
        else
        {
            return $this->render('novousuario') ;  
        }

    }

    public function actionCreate()
    {
        $model = new Usuario();
        
        if ($model->load(Yii::$app->request->post())){
            
            //verifica se o CPF já está cadastrado
            $usuario = Usuario::find()->where(['cpf' => $model->cpf ])->one();

            if( $usuario != null )
            {
                $model->addError('cpf','O CPF informado já está cadastrado...');
                return $this->render('create', ['model' => $model]);
            }

            //verifica se o EMAIL já está cadastrado
            $usuario = Usuario::find()->where(['email' => $model->email ])->one();

            if( $usuario != null )
            {
                $model->addError('email','O EMAIL informado já está cadastrado...');
                return $this->render('create', ['model' => $model]);
            }

            $model->password = md5($model->password);
	    $model->password_repeat = md5($model->password_repeat);
            
            if($model->save())
				return $this->redirect(['login']);
			else
				return $this->render('create', ['model' => $model,]);
			
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionRecuperarsenha()
    {

        
        if ( Yii::$app->request->post()) 
        {
            $email = Yii::$app->request->post('email');

            $usuario = Usuario::find()->where(['email'=>$email])->one();

            if($usuario!=null) //se o usuario com email informado existe...
            {
                
                //gera o token de troca senha
                $usuario->generatePasswordResetToken();
                
				if($model->save()){
					
					//prepara o email com o link
					$domain = 'sandbox081c87f9e07a4f669f46f26af7261c2a.mailgun.org';
					$key = 'key-f0dc85b59a45bcda5373019f605ce034';
					$mailgun = new \MailgunApi( $domain, $key );
                
					$message = $mailgun->newMessage();
                
					$message->setFrom('sistemas@icomp.ufam.edu.br', 'Admin-Atv Complementares');
					$message->addTo( $usuario->email, $usuario->name); //destinatario...
					$message->setSubject('Nova Senha');

					$url = Url::to(['login/resetpassword', 'token' => $usuario->password_reset_token] , true) ;
                
					$message->setHtml($this->renderPartial('email', ['usuario' => $usuario->name, 'url' => $url]), []);

					$message->send();

					return $this->render('senhaenviada');
				}
				else
					return $this->render('recuperarsenha');
            }
            else
            {
                return $this->render('emailnaoencontrado');
            }
        }
        else
        {   //se for metodo GET chama a view para informar o email
            return $this->render('recuperarsenha');
        }
    }
    
    /**
     * Reseta a senha do usuario informado.
     */
    public function actionResetpassword()
    {

        if ( Yii::$app->request->post() ) 
        {
            
            $model = new Usuario();
            
            //busca o usuario pelo ID
            $id = Yii::$app->request->post('id');
            
            $model = Usuario::find()->where(['id'=>$id])->one();
            
            $model->password = md5(Yii::$app->request->post('senhanova'));
            
            $model->save(false);

            return $this->goHome();
        }
        else
        {
            $model = new Usuario();
            
            //busca o usuario pelo token

views/login/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Curso;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin([
    'method' => 'post',
    'action' => ['login/create'],
    ]); ?>
    
    <div class="col-md-12">
        
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true])->widget(\yii\widgets\MaskedInput::className(), ['mask' => '999.999.999-99',]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'matricula')->textInput(['maxlength' => true]) ?>
  
    <?= $form->field($model, 'curso_id')
                    ->dropDownList(ArrayHelper::map(\app\models\Curso::find()->all(), 'id', 'nome'), ['prompt'=>'Selecione']); ?>

    <?php 
        if( $model->siape != null ) 
        {
            echo $form->field($model, 'siape')->textInput(['maxlength' => true]);
        }
    ?>
   
    <?php
    
    if(isset(Yii::$app->user->identity))
    {
        
        if(Yii::$app->user->identity->isAdmin)
        {
            
            $items = ['Secretaria'=>'Secretaria', 'Coordenador'=>'Coordenador', 'admin'=>'Admin'];
            
            echo $form->field($model, 'perfil')->dropDownList($items, ['prompt'=>'Selecione']);
            
        }
        
    }
    //se não estiver logado o perfil do usuario será Aluno
    else
    {
        echo $form->field($model, 'perfil')->hiddenInput(['value' => 'Aluno'])->label(false);
    }

    ?>    
    
    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
	<?= $form->field($model, 'password_repeat')->passwordInput()->label("Repetir Senha:")  ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Salvar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a('Cancelar', ['login/login'], ['class' => 'btn btn-danger']) ?>
    </div>
</div>
    <?php ActiveForm::end(); ?>

</div>

views/login/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Usuario */

$this->title = 'Novo Usuário';
?>
<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
</section>
<section class="content">
<div class="box box-success"> 
<div class="usuario-create box-body">

   
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>        
		<?php 

            if(isset($erro))
            {
                echo "<p class='col-sm-12 alert alert-danger'>";
                echo $erro ;
                echo "</p>";
            }
        ?>

</div>
</div>
</section>
</div>
<div class="col-md-4"></div>

views/login/email.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<div class="usuario-index">

    <html>
    <head>
        <title>Email teste</title>

        <meta charset="UTF-8">

    </head>

    <body>


    <table>

        <tbody>

        <tr>
            <td style="color:#153643;font-size:18px;font-weight:bold;font-family:'Open Sans',sans-serif;border-bottom:#bbbbbb solid 1px" align="center" bgcolor="#F7F7F7">
                <img tabindex="0" class="CToWUd a6T" src="http://icomp.ufam.edu.br/images/sampledata/ja_university/sistema-icomp.png" alt="logo icomp" style="display:block" height="auto" width="auto"><div style="opacity: 0.01; left: 690.5px; top: 201px;" dir="ltr" class="a6S"><div data-tooltip="Fazer o download" data-tooltip-class="a1V" id=":fc" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Fazer o download do anexo "><div class="aSK J-J5-Ji aYr"></div></div></div>
            </td>
        </tr>
        <tr>
            <td style="padding:40px 30px 40px 30px" bgcolor="#FFFFFF">
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tbody><tr>
                        <td style="color:#153643;font-family:'Open Sans',sans-serif;font-size:14px">
                            <b>Sistema de Atividades Complementares</b>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:20px 0 0 0;color:#153643;font-family:'Open Sans',sans-serif;font-size:12px;line-height:20px">
                            <p>
                                Olá, <?= $usuario ?> <br/><br/><br/>

                                Você solicitou a alteração da senha através do<strong>Sistema de Atividades Complementares.</strong></p>

                            <br/>

                            <p style="text-align:center;margin:40px 0 40px 0">
                                <strong><a href="<?= $url ?>" style="background:#9c6132;color:#fff;padding:10px 30px 10px 30px;text-decoration:none" target="_blank">Clique neste link!</a></strong>
                            </p>

                            <br/>
                            <p>Se você não solicitou a troca da senha, desconsidere este email.</p>
                        </td>
                    </tr>
                    </tbody></table>
            </td>
        </tr>
        <tr>
            <td style="padding:30px 30px 30px 30px;border-top:#bbbbbb solid 1px" bgcolor="#F7F7F7">
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tbody><tr>
                        <td style="color:#133543;font-family:'Open Sans',sans-serif;font-size:12px;font-weight:bold" width="75%">
                            © 2015 ICOMP<br>
                            <span style="font-size:10px;color:#bbbbbb;font-weight:700">
                                Copyright © 2015 Instituto de Computação - Universidade Federal do Amazonas. <br/>
                                Todos os direitos reservados. <br/>
                                v1.0 <br/>
                            </span>
                        </td>
                        <td align="right" width="25%">
                            <table border="0" cellpadding="0" cellspacing="0">
                                <tbody><tr>
                                    <td style="font-family:'Open Sans',sans-serif;font-size:12px;font-weight:bold">
                                        <a href="http://www.twitter.com/ufam" style="color:#ffffff" target="_blank">
                                            <img src="https://urionlinejudge.r.worldssl.net/judge/img/email/twitter.gif" alt="Twitter" style="display:block" border="0" height="38" width="38">
                                        </a>
                                    </td>
                                    <td style="font-size:0;line-height:0" width="20">&nbsp;</td>
                                    <td style="font-family:'Open Sans',sans-serif;font-size:12px;font-weight:bold">
                                        <a href="https://www.facebook.com/groups/188204881205188" style="color:#ffffff" target="_blank">
                                            <img src="https://urionlinejudge.r.worldssl.net/judge/img/email/facebook.gif" alt="Facebook" style="display:block" border="0" height="38" width="38">
                                        </a>
                                    </td>
                                </tr>
                                </tbody></table>
                        </td>
                    </tr>
                    </tbody></table>
            </td>
        </tr>
        </tbody>
        <table>

    </body>
    </html>














    <div class='foot'>
        <p>
            <small>

            </small>
        </p>
    </div>

</div>

views/login/emailnaoencontrado.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Recuperar senha';
?>
<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
</section>
<section class="content">
	<div class="box box-success">
		<div class=" box-body">


		    <p>Usuário não cadastrado com este email...</p>

		</div>
	</div>
</section>
<div class="col-md-4"></div>

views/login/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php
    $this->registerJsFile(Yii::$app->request->baseUrl.'/js/validaCPF.js',['depends' => [\yii\web\JqueryAsset::className()]]);
?>


   <div class="login-box">
      <div class="login-logo">
         <a href="#"><b>Atividades Acadêmicas</b></a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
      <p class="login-box-msg">Insira seu CPF e a senha para entrar</p>
        <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'fieldConfig' => ['labelOptions' => ['class' => 'control-label'],
        ],
        ]); ?>
         
        <?= $form->field($model, 'cpf',['template' => "{label}\n{input}\n{hint}\n{error}"])->widget(\yii\widgets\MaskedInput::className(), [
    'mask' => '999.999.999-99',])->textInput(array('placeholder' => 'CPF','class'=>'form-control'))->label(false)?>

        <?= $form->field($model, 'password')->passwordInput(array('placeholder' => 'Senha'))->label(false)?>
        
        <div class="row">
            <div class="col-xs-4 pull-right">
                 <button type="submit" name="login-button" class="btn btn-success btn-block btn-flat">Entrar</button>
            </div><!-- /.col -->
        </div>
        
        <?php

    ActiveForm::end(); ?>
        

        <a href="?r=login/recuperarsenha">Solicitar Nova Senha</a><br>
        <a href="?r=login/novousuario" class="text-center">Registrar aluno</a>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

  

views/login/novasenha.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->registerJsFile(Yii::$app->request->baseUrl.'/js/compara.js',['depends' => [\yii\web\JqueryAsset::className()]]);

$this->title = 'Alterar Senha';
?>

<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-body">

            <?php $form = ActiveForm::begin(); ?>
                <div class="form-group">
                    <label for="senhanova" class="control-label" >Nova Senha</label>
                    <input type="password" id="pw1" name="senhanova" class="form-control" placeholder="Informe a nova senha" />
                </div>
                <div class="form-group">
                    <label for="senhanova2" class="control-label" >Confirmar senha</label>
                    <input type="password" id="pw2" name="senhanova2" class="form-control" placeholder="Repita sua nova senha" />
                </div>
                    
                <div class="form-group">
                    <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
                    
                </div>

                <div class="col-xs-12">
                    <p class="alert alert-danger" id="status" hidden="true"></p>
                </div>
                <?= Html::input('hidden', 'token', $model->password_reset_token ) ?>
                <?= Html::input('hidden', 'id', $model->id ) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</section>

views/login/novousuario.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
?>

<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
    <section class="content-header">
        <h1>Novo Usuário</h1>
    </section>
    <section class="content">
        <div class="box box-success"> 
            <div class="box-body"> 

                <?php $form = ActiveForm::begin(); ?>

                   <div class="col-xs-12">
                         <div class="form-group">
                             <label for="cpf" class="control-label" >CPF</label>
                             
                             <?php echo MaskedInput::widget([
                                'name' => 'cpf',
                                'mask' => ['999.999.999-99']
                            ]); ?>
                             <!--<input type="text" name="cpf" class="form-control" id="cpf" placeholder="Digite seu CPF"/>-->
                         </div>

                        <div class="form-group">
                            <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
                             <?= Html::a('Cancelar', ['login/login'], ['class' => 'btn btn-danger']) ?>
                        </div>


                        <?php 

                            if(isset($erro))
                            {
                                echo "<p class='col-sm-12 alert alert-danger'>";
                                echo $erro ;
                                echo "</p>";
                            }
                        ?>
                        </p>
                    </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </section>
</div>
<div class="col-md-4"></div>

views/login/recuperarsenha.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php
$this->title = 'Solicitar Nova Senha';
?>
<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
</section>
<section class="content">
<div class="box box-success">
	<div class=" box-body">
	<?php $form = ActiveForm::begin(); ?>

	     <div class="form-group">
            <label for="email" class="control-label" >Email</label>
            <input type="text" name="email" class="form-control" id="email" placeholder="Digite seu email de cadastro" />
         </div>

	    <div class="form-group">
	        <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
	         <?= Html::a('Cancelar', ['login/login'], ['class' => 'btn btn-danger']) ?>
	    </div>

	<?php ActiveForm::end(); ?>
</div>
</div>
</section>
</div>
<div class="col-md-4"></div>

views/login/senhaenviada.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Solicitar Nova Senha';
?>
<div class="col-md-4"></div>
<div class="col-xs-12 col-md-4">
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
</section>
<section class="content">
<div class="box box-success">
	<div class=" box-body">

	<p class='col-xs-12 alert alert-success'>Nova senha enviada, verifique seu email!</p>

	</div>
	</div>
</section>

views/login/solicitaemail.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<section class="content">
<?php $form = ActiveForm::begin(); ?>

    <h2>Informe seu Email</h2>
    <div class="form-group">
        <?= Html::input('text','email') ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
         <?= Html::a('Cancelar', ['login/login'], ['class' => 'btn btn-danger']) ?>
    </div>

<?php ActiveForm::end(); ?>
</section>