models/Periodo.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "periodo".
 *
 * @property integer $id
 * @property string $codigo
 * @property string $dtInicio
 * @property string $dtTermino
 */
class Periodo extends \yii\db\ActiveRecord
{
    public $traducao_isAtivo;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'periodo';
    }

    public function getSolicitacoes()
    {
        return $this->hasMany(Solicitacao::className(), ['periodo_id' => 'id']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['codigo', 'dtInicio', 'dtTermino', 'dtInicioInscMonitoria','dtTerminoInscMonitoria'], 'required', 'message'=> 'Este campo é obrigatório'],
			//[['dtInicio','dtTermino','dtInicioInscMonitoria','dtTerminoInscMonitoria'], 'date', 'format' => 'php:Y-m-d', 'message'=> 'O formato desta data é inválido'],
			[['dtInicio','dtTermino','dtInicioInscMonitoria','dtTerminoInscMonitoria'], 'default', 'value' => null],
			['dtInicio','validateDates'],
            [['justificativaPlanoSemestral'], 'string'],
            [['isAtivo'], 'integer'],
            [['codigo'], 'string', 'max' => 10],
            [['codigo'], 'unique', 'message'=>'Código de período já cadastrado'],
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'codigo' => 'Código',
            'dtInicio' => 'Data de Início',
            'dtTermino' => 'Data de Término',
            'isAtivo'  => 'Período Corrente',
            'dtInicioInscMonitoria' => 'Início da Inscrição para Monitoria',
            'dtTerminoInscMonitoria' => 'Término da Inscrição para Monitoria',
            'justificativaPlanoSemestral' => 'Justificativas do Plano Semestral'
        ];
    }
    
    public function afterFind()
    {
        switch ($this->isAtivo)
        {
            case 0:
                $this->traducao_isAtivo = 'Não';
                break;
            case 1:
                $this->traducao_isAtivo = 'Sim';
                break;
        }
    }
	
	function checkData($data) {
		return (date('d-m-Y', strtotime($data)) == $data);
    }

	public function validateDates(){
		$erro = false;
		
		if(!Periodo::checkData($this->dtInicio)){
			$this->dtInicio = "";
			$this->addError('dtInicio','Por favor, informe uma data de início válida no formato DD-MM-AAAA.');
			$erro = true;
		}
		else{
			$this->dtInicio = Yii::$app->formatter->asDate(strtotime($this->dtInicio), 'php:Y-m-d');
		}
		if(!Periodo::checkData($this->dtTermino)){
			$this->dtTermino = "";
			$this->addError('dtTermino','Por favor, informe uma data de término válida no formato DD-MM-AAAA.');
			$erro = true;
		}	
		else{
			$this->dtTermino = Yii::$app->formatter->asDate(strtotime($this->dtTermino), 'php:Y-m-d');
		}
		
		if($erro == false){
			if(strtotime($this->dtTermino) <= strtotime($this->dtInicio)){
				$this->addError('dtInicio','Por favor, informe uma data de início anterior à data de término');
				$this->addError('dtTermino','Por favor, informe uma data de término posterior à data de início');
			}
		}

		$erroMonitoria = false;
		if(!Periodo::checkData($this->dtInicioInscMonitoria)){
			$this->dtInicioInscMonitoria = "";
			$this->addError('dtInicioInscMonitoria','Por favor, informe uma data de início de monitoria válida no formato DD-MM-AAAA.');
			$erroMonitoria = true;
		}
		else{
			$this->dtInicioInscMonitoria = Yii::$app->formatter->asDate(strtotime($this->dtInicioInscMonitoria), 'php:Y-m-d');
		}
		
		if(!Periodo::checkData($this->dtTerminoInscMonitoria)){
			$this->dtTerminoInscMonitoria = "";
			$this->addError('dtTerminoInscMonitoria','Por favor, informe uma data de término de monitoria válida no formato DD-MM-AAAA.');
			$erroMonitoria = true;
		}
		else{
			$this->dtTerminoInscMonitoria = Yii::$app->formatter->asDate(strtotime($this->dtTerminoInscMonitoria), 'php:Y-m-d');
		}
		
		if(!$erroMonitoria){
			if(strtotime($this->dtTerminoInscMonitoria) <= strtotime($this->dtInicioInscMonitoria)){
				$this->addError('dtInicioInscMonitoria','Por favor, informe uma data de início da inscrição de monitoria anterior à data de término');
				$this->addError('dtTerminoInscMonitoria','Por favor, informe uma data de término da inscrição de monitoria posterior à data de início');
			}
			
			if(!$erro){
				if(strtotime($this->dtInicioInscMonitoria) < strtotime($this->dtInicio) || strtotime($this->dtInicioInscMonitoria) > strtotime($this->dtTermino)){
					$this->addError('dtInicioInscMonitoria','A data de início da inscrição de monitoria deve ser dentro do intervalo do período');
				}
				if(strtotime($this->dtTerminoInscMonitoria) < strtotime($this->dtInicio) || strtotime($this->dtTerminoInscMonitoria) > strtotime($this->dtTermino)){
					$this->addError('dtTerminoInscMonitoria','A data de término da inscrição de monitoria deve ser dentro do intervalo do período');
				}
			}
		}
	}
	
}

controllers/PeriodoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Periodo;
use app\models\PeriodoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\db\Command;

/**
 * PeriodoController implements the CRUD actions for Periodo model.
 */
class PeriodoController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','index', 'update', 'view', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create','index', 'update', 'view', 'delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if(!Yii::$app->user->isGuest)
                            {
                                if ( Yii::$app->user->identity->perfil === 'Secretaria' ) 
                                {
                                    return Yii::$app->user->identity->perfil == 'Secretaria'; 
                                }
                                elseif ( Yii::$app->user->identity->perfil === 'Coordenador' ) 
                                {
                                    return Yii::$app->user->identity->perfil == 'Coordenador'; 
                                }
                                elseif ( Yii::$app->user->identity->perfil === 'admin' ) 
                                {
                                    return Yii::$app->user->identity->perfil == 'admin'; 
                                }
                                return Yii::$app->user->identity->isAdmin == 1 ;    
                            }
                        }
                    ], 
                ],
            ],           
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Periodo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PeriodoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'erro' => ($this->getPeriodoAtivo() == null ? 1 : 0),
        ]);
    }

    /**
     * Displays a single Periodo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Periodo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Periodo();

        if ($model->load(Yii::$app->request->post())) {

            // Quando marcado como o período corrente, então o demais não podem ser o corrente.
            if ($model->isAtivo == 1)
            {
                Yii::$app->db->createCommand()->update('periodo', ['isAtivo' => 0], 'id<>'.$model->id)->execute();
            }

            //$model->dtInicio = Yii::$app->formatter->asDate(strtotime($model->dtInicio), 'php:Y-m-d');
            //$model->dtTermino = Yii::$app->formatter->asDate(strtotime($model->dtTermino), 'php:Y-m-d');
            //$model->dtInicioInscMonitoria = Yii::$app->formatter->asDate(strtotime($model->dtInicioInscMonitoria), 'php:Y-m-d');
            //$model->dtTerminoInscMonitoria = Yii::$app->formatter->asDate(strtotime($model->dtTerminoInscMonitoria), 'php:Y-m-d');

            if($model->save())
				return $this->redirect(['view', 'id' => $model->id]);
			else
				return $this->render('create', ['model' => $model,]);

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Periodo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())){ 

            // Quando marcado como o período corrente, então o demais não podem ser o corrente.
            if ($model->isAtivo == 1)
            {
                Yii::$app->db->createCommand()->update('periodo', ['isAtivo' => 0], 'id<>'.$id)->execute();
            }

            //$model->dtInicio = Yii::$app->formatter->asDate(strtotime($model->dtInicio), 'php:Y-m-d');
            //$model->dtTermino = Yii::$app->formatter->asDate(strtotime($model->dtTermino), 'php:Y-m-d');
            //$model->dtInicioInscMonitoria = Yii::$app->formatter->asDate(strtotime($model->dtInicioInscMonitoria), 'php:Y-m-d');
            //$model->dtTerminoInscMonitoria = Yii::$app->formatter->asDate(strtotime($model->dtTerminoInscMonitoria), 'php:Y-m-d');
			
            if($model->save())
				return $this->redirect(['view', 'id' => $model->id]);
			else
				return $this->render('update', ['model' => $model,]);
				
        } else {
            return $this->render('update', ['model' => $model,]);
        }
    }

    /**
     * Deletes an existing Periodo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Periodo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Periodo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Periodo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function getPeriodoAtivo()
    {
        return Periodo::findOne(['isAtivo' => 1]);
    }
}

views/periodo/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Periodo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="periodo-form">
    <?php $form = ActiveForm::begin(); ?>
     <div class="col-md-4">
   
        <?= $form->field($model, 'codigo')->textInput(['maxlength' => true])->widget(\yii\widgets\MaskedInput::className(), ['mask' => '9999/9',]) ?>
        <?= $form->field($model, 'dtInicio')->widget(\yii\jui\DatePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'language' => 'pt-BR',
                'dateFormat' => 'dd-MM-y',
        ]) ?>
        <?= $form->field($model, 'dtTermino')->widget(\yii\jui\DatePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'language' => 'pt-BR',
                'dateFormat' => 'dd-MM-y',
        ]) ?>
        <?= $form->field($model, 'dtInicioInscMonitoria')->widget(\yii\jui\DatePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'language' => 'pt-BR',
                'dateFormat' => 'dd-MM-y',
        ]) ?>
        <?= $form->field($model, 'dtTerminoInscMonitoria')->widget(\yii\jui\DatePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'language' => 'pt-BR',
                'dateFormat' => 'dd-MM-y',
        ]) ?>

        <?= $form->field($model, 'isAtivo')->checkbox() ?>

        <?= Html::submitButton($model->isNewRecord ? 'Salvar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a('Cancelar', ['periodo/index'], ['class' => 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
        $('#periodo-dtinicio').on('change', function () {
        var test = $(this).datepicker('getDate');
        var testm = new Date(test.getTime());
        testm.setDate(testm.getDate() + 1);

        $("#periodo-dttermino").datepicker("option", "minDate", testm);
    });
</script>

<script>
        $('#periodo-dtinicioinscmonitoria').on('change', function () {
        var dtini2 = $(this).datepicker('getDate');
        var dtini2m = new Date(dtini2.getTime());
        dtini2m.setDate(dtini2m.getDate());

        $("#periodo-dtterminoinscmonitoria").datepicker("option", "minDate", dtini2m);
    });
</script>

views/periodo/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PeriodoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="periodo-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'codigo') ?>

    <?= $form->field($model, 'dtInicio') ?>

    <?= $form->field($model, 'dtTermino') ?>

    <?= $form->field($model, 'dtInicioInscMonitoria') ?>

    <?= $form->field($model, 'dtTerminoInscMonitoria') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/periodo/create.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $model app\models\Periodo */
$this->title = 'Cadastro de Período';
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=periodo/index"><i class="fa fa-calendar"></i> Período</a></li>
        <li class="active"><a href="?r=periodo/create">Cadastro</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success"> 
<div class="periodo-create box-body">
  
  <?= $this->render('_form', [
  'model' => $model,
  ]) ?>
  
</div>
</div>
</section>

views/periodo/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Periodo;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PeriodoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lista de Períodos';
?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=periodo/index"><i class="fa fa-calendar"></i> Período</a></li>
        <li class="active"><a href="?r=periodo/index">Lista</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success">    
<div class="periodo-index box-body">

    <?php if(isset($erro) && $erro == 1) { ?>
        <p id="alerta" class='col-xs-12 alert alert-danger'><?php echo "<strong>Atenção!</strong><br>"; echo "Não existe período ativo no sistema. Ative ou cadastre o período corrente."; ?></p>
        <script>
           setTimeout(function(){ $('#alerta').fadeOut(); }, 10000);
        </script>
    <?php } ?>

    <p>
        <?= Html::a('Novo Período', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary'=>'',
        'columns' => [
            'codigo',
            [
            'attribute' => 'dtInicio',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtTermino',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtInicioInscMonitoria',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtTerminoInscMonitoria',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
                'attribute' => 'isAtivo',
                'label'=>'Período Corrente', 
                'format' => 'raw',
                'value' => function ($model) {
                        if ($model->isAtivo == 1)
                            return '<div style="text-align:center"> <span class="glyphicon glyphicon-ok"></span> </div>';
                },
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>
</div>
</section>

views/periodo/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Periodo */

$this->title = $model->codigo;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=periodo/index"><i class="fa fa-calendar"></i> Período</a></li>
        <li class="active"><a href="?r=periodo/index">Lista</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success"> 
<div class="periodo-update box-body">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>
</section>

views/periodo/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Periodo */

$this->title = $model->codigo;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Período: <?= Html::encode($this->title) ?></h1>
    <ol class="breadcrumb">
        <li><a href="?r=periodo/index"><i class="fa fa-calendar"></i> Período</a></li>
        <li class="active"><a href="?r=periodo/index">Lista</a></li>
    </ol>
</section>
<section class="content">
<div class="box box-success"> 
<div class="periodo-view box-body">

    <p>
        <?= Html::a('<span class="glyphicon glyphicon-arrow-left"></span> Voltar', ['index'], ['class' => 'btn btn-warning']) ?>
		<?= Html::a('Editar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Excluir', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Você deseja deletar este item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'codigo',
            [
            'attribute' => 'dtInicio',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtTermino',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtInicioInscMonitoria',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
            'attribute' => 'dtTerminoInscMonitoria',
            'format' => ['date', 'php:d-m-Y']
            ],
            [
                'label' => 'Período Corrente',
                'value' => $model->traducao_isAtivo
            ],
        ],
    ]) ?>

</div>
</div>
</section>